.PHONY: clean All

All:
	@echo "----------Building project:[ custom_exceptions - Debug ]----------"
	@cd "custom_exceptions" && "$(MAKE)" -f  "custom_exceptions.mk"
clean:
	@echo "----------Cleaning project:[ custom_exceptions - Debug ]----------"
	@cd "custom_exceptions" && "$(MAKE)" -f  "custom_exceptions.mk" clean
