.PHONY: clean All

All:
	@echo "----------Building project:[ template - Debug ]----------"
	@cd "template" && "$(MAKE)" -f  "template.mk"
clean:
	@echo "----------Cleaning project:[ template - Debug ]----------"
	@cd "template" && "$(MAKE)" -f  "template.mk" clean
