.PHONY: clean All

All:
	@echo "----------Building project:[ nested_template - Debug ]----------"
	@cd "nested_template" && "$(MAKE)" -f  "nested_template.mk"
clean:
	@echo "----------Cleaning project:[ nested_template - Debug ]----------"
	@cd "nested_template" && "$(MAKE)" -f  "nested_template.mk" clean
