.PHONY: clean All

All:
	@echo "----------Building project:[ writing_binaries - Debug ]----------"
	@cd "writing_binaries" && "$(MAKE)" -f  "writing_binaries.mk"
clean:
	@echo "----------Cleaning project:[ writing_binaries - Debug ]----------"
	@cd "writing_binaries" && "$(MAKE)" -f  "writing_binaries.mk" clean
