.PHONY: clean All

All:
	@echo "----------Building project:[ assignment - Debug ]----------"
	@cd "assignment" && "$(MAKE)" -f  "assignment.mk"
clean:
	@echo "----------Cleaning project:[ assignment - Debug ]----------"
	@cd "assignment" && "$(MAKE)" -f  "assignment.mk" clean
