.PHONY: clean All

All:
	@echo "----------Building project:[ maps - Debug ]----------"
	@cd "maps" && "$(MAKE)" -f  "maps.mk"
clean:
	@echo "----------Cleaning project:[ maps - Debug ]----------"
	@cd "maps" && "$(MAKE)" -f  "maps.mk" clean
