.PHONY: clean All

All:
	@echo "----------Building project:[ fptr - Debug ]----------"
	@cd "fptr" && "$(MAKE)" -f  "fptr.mk"
clean:
	@echo "----------Cleaning project:[ fptr - Debug ]----------"
	@cd "fptr" && "$(MAKE)" -f  "fptr.mk" clean
